name: flutter_google_ai_gemini
description: flutter_google_ai_gemini
version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.0.3
  google_generative_ai: ^0.4.4
  flutter_dotenv: ^5.1.0
  file: ^6.1.4
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
    uses-material-design: true
    assets:
      - assets/.env



